name: Go
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
  branches:
    - 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version: '1.25.x'
      #- name: Install dependencies
      #  run: go get .
      - name: Format
        run: go fmt ./...
      - name: Build
        run: go build -v ./...
      - name: Test with the Go CLI
        run: go test
