name: Go
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version: '1.25.x'
      #- name: Install dependencies
      #  run: go get . # go mod tidy
      - name: Format
        run: make format
      - name: Build
        run: make build
      - name: Test with the Go CLI
        run: make test
      - name: Generate Coverage Report # this does rerun tests
        run: make cover
      - name: Check Coverage Percent
        env:
          THRESHOLD: "90.0"
          COVERAGE_FILE: "./out/coverage.out"
        run: |
          bash ./scripts/coverage_threshold.bash $COVERAGE_FILE $THRESHOLD
